apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  # https://kyverno.io/policies/pod-security/baseline/disallow-host-path/disallow-host-path/
  name: disallow-host-path
  annotations:
    policies.kyverno.io/title: Disallow hostPath (PSP 1.20.05)
    policies.kyverno.io/category: SAP TOP-X
    policies.kyverno.io/severity: medium
    kyverno.io/kyverno-version: 1.6.0
    kyverno.io/kubernetes-version: "1.22-1.24"
    policies.kyverno.io/subject: Pod,Volume
    policies.kyverno.io/description: >-
      HostPath volumes let Pods use host directories and volumes in containers.
      Using host resources can be used to access shared data or escalate privileges
      and should not be allowed. This policy ensures no hostPath volumes are in use.
      https://wiki.wdf.sap.corp/wiki/display/itsec/Kubernetes+Container+Orchestration+-+Hardening#KubernetesContainerOrchestrationHardening-1.20.05Ensurepathsallowedtobemountedfromhostisrestricted
spec:
  validationFailureAction: {{ .Values.policies.disallowHostPath.validationFailureAction }}
  background: true
  failurePolicy: {{ .Values.policies.failurePolicy }}
  rules:
    - name: host-path
      match:
        any:
          - resources:
              kinds:
                - Pod
      preconditions:
        all:
          {{- include "whitelist-rule" "disallow-host-path" | nindent 10 }}
      validate:
        message: >-
          HostPath volumes are forbidden. The field spec.volumes[*].hostPath must be unset.
        pattern:
          spec:
            =(volumes):
              - X(hostPath): "null"
