apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  # https://kyverno.io/policies/pod-security/restricted/disallow-capabilities-strict/disallow-capabilities-strict/
  name: disallow-capabilities-strict
  annotations:
    policies.kyverno.io/title: Disallow Capabilities Strict (PSP 1.20.06)
    policies.kyverno.io/category: SAP TOP-X
    policies.kyverno.io/severity: medium
    policies.kyverno.io/minversion: 1.6.0
    kyverno.io/kyverno-version: 1.6.0
    kyverno.io/kubernetes-version: "1.22-1.24"
    policies.kyverno.io/subject: Pod
    policies.kyverno.io/description: >-
      Adding capabilities other than `NET_BIND_SERVICE` is disallowed. In addition,
      all containers must explicitly drop `ALL` capabilities.
      Further information can be found at https://wiki.wdf.sap.corp/wiki/display/itsec/Kubernetes+Container+Orchestration+-+Hardening#KubernetesContainerOrchestrationHardening-1.20.06Ensureusageofcapabilitiesisrestrictedtoaminimum
spec:
  validationFailureAction: {{ .Values.policies.disallowCapabilitiesStrict.validationFailureAction }}
  background: true
  failurePolicy: {{ .Values.policies.failurePolicy }}
  rules:
    - name: require-drop-all
      match:
        any:
          - resources:
              kinds:
                - Pod
      preconditions:
        all:
          {{- include "whitelist-rule" "disallow-capabilities-strict" | nindent 10 }}
          - key: {{ `{{ request.operation || 'BACKGROUND' }}` | quote }}
            operator: NotEquals
            value: DELETE
      validate:
        message: >-
          Containers must drop `ALL` capabilities.
        foreach:
          - list: request.object.spec.[ephemeralContainers, initContainers, containers][]
            deny:
              conditions:
                all:
                  - key: ALL
                    operator: AnyNotIn
                    value: {{ "{{ element.securityContext.capabilities.drop[].to_upper(@) || `[]` }}" | quote }}
    - name: adding-capabilities-strict
      match:
        any:
          - resources:
              kinds:
                - Pod
      preconditions:
        all:
          {{- include "whitelist-rule" "disallow-capabilities-strict" | nindent 10 }}
          - key: {{ `{{ request.operation || 'BACKGROUND' }}` | quote }}
            operator: NotEquals
            value: DELETE
      validate:
        message: >-
          Any capabilities added other than NET_BIND_SERVICE are disallowed.
        foreach:
          - list: request.object.spec.[ephemeralContainers, initContainers, containers][]
            deny:
              conditions:
                all:
                  - key: {{ "{{ element.name || '' }}" | quote }}
                    operator: NotEquals
                    value: "istio-init"
                  - key: {{ "{{ element.securityContext.capabilities.add[].to_upper(@) || `[]` }}" | quote }}
                    operator: AnyNotIn
                    value:
                      - NET_BIND_SERVICE
                      - ''
