apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  # https://kyverno.io/policies/pod-security/baseline/disallow-host-ports/disallow-host-ports/
  name: disallow-host-ports
  annotations:
    policies.kyverno.io/title: Disallow hostPorts (PSP 1.20.04)
    policies.kyverno.io/category: SAP TOP-X
    policies.kyverno.io/severity: medium
    kyverno.io/kyverno-version: 1.6.0
    kyverno.io/kubernetes-version: "1.22-1.24"
    policies.kyverno.io/subject: Pod
    policies.kyverno.io/description: >-
      Access to host ports allows potential snooping of network traffic and should not be
      allowed, or at minimum restricted to a known list. This policy ensures the `hostPort`
      field is unset or set to `0`.
      Further information can be found at https://wiki.wdf.sap.corp/wiki/display/itsec/Kubernetes+Container+Orchestration+-+Hardening#KubernetesContainerOrchestrationHardening-1.20.04Ensuretheusageofcontainerfeaturesisrestricted.
spec:
  validationFailureAction: {{ .Values.policies.disallowHostPorts.validationFailureAction }}
  background: true
  failurePolicy: {{ .Values.policies.failurePolicy }}
  rules:
    - name: host-ports-none
      match:
        any:
          - resources:
              kinds:
                - Pod
      preconditions:
        all:
          {{- include "whitelist-rule" "disallow-host-ports" | nindent 10 }}
      validate:
        message: >-
          Use of host ports is disallowed. The fields spec.containers[*].ports[*].hostPort
          , spec.initContainers[*].ports[*].hostPort, and spec.ephemeralContainers[*].ports[*].hostPort
          must either be unset or set to `0`.
        pattern:
          spec:
            =(ephemeralContainers):
              - =(ports):
                  - =(hostPort): 0
            =(initContainers):
              - =(ports):
                  - =(hostPort): 0
            containers:
              - =(ports):
                  - =(hostPort): 0
