apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  # https://kyverno.io/policies/other/require_pdb/require_pdb/
  name: require-pdb
  annotations:
    policies.kyverno.io/title: Require PodDisruptionBudget
    policies.kyverno.io/category: Sample
    policies.kyverno.io/minversion: 1.3.6
    policies.kyverno.io/subject: Deployment, PodDisruptionBudget
    policies.kyverno.io/description: >-
      PodDisruptionBudget resources are useful to ensuring minimum availability
      is maintained at all times. This policy checks all incoming Deployments
      to ensure they have a matching, preexisting PodDisruptionBudget.
spec:
  validationFailureAction: {{ .Values.policies.requirePDB.validationFailureAction }}
  background: true
  failurePolicy: {{ .Values.policies.failurePolicy }}
  rules:
    - name: require-pdb
      match:
        resources:
          kinds:
            - Deployment
      preconditions:
        all:
          {{- include "whitelist-rule" "require-pdb" | nindent 10 }}
      context:
        - name: pdb_count
          apiCall:
            urlPath: {{ `/apis/policy/v1/namespaces/{{request.namespace}}/poddisruptionbudgets` | quote }}
            jmesPath: {{ "items[?label_match(spec.selector.matchLabels, `{{request.object.spec.template.metadata.labels}}`)] | length(@)" | quote }}
      validate:
        message: "There is no corresponding PodDisruptionBudget found for this Deployment."
        deny:
          conditions:
            any:
              - key: {{ `{{ pdb_count }}` | quote }}
                operator: LessThan
                value: 1
