apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: restrict-image-registries
  annotations:
    policies.kyverno.io/title: Restrict Public/Unknown Registries
    policies.kyverno.io/category: Best Practices, Best Practices
    policies.kyverno.io/severity: medium
    policies.kyverno.io/minversion: 1.6.0
    kyverno.io/kubernetes-version: "1.26"
    policies.kyverno.io/subject: Pod
    policies.kyverno.io/description: >-
      Images from Public, Unknown registries can be of dubious quality and may not be
      scanned and secured, representing a high degree of risk. This also sometimes causes ratelimiting.
      Requiring use of known, approved registries helps reduce threat exposure
      by ensuring image pulls only come from them and also the performance issues.
      This policy audit the container images originate from the registry `*docker.` or
      `quay.io`. Use of this policy requires customization to define your allowable registries.
spec:
  validationFailureAction: {{ .Values.policies.restrictImageRegistries.validationFailureAction }}
  background: true
  failurePolicy: {{ .Values.policies.failurePolicy }}
  rules:
  - name: validate-registries
    match:
      any:
      - resources:
          kinds:
          - Pod
    validate:
      message: "Public/Unknown image registries are prohibited."
      pattern:
        spec:
          =(ephemeralContainers):
          - image: "*docker.io/* | *quay.io/* "
          =(initContainers):
          - image: "*docker.io/* | *quay.io/* "
          containers:
          - image: "*docker.io/* | *quay.io/* "
