{{- if .Values.restartKyvernoPods.enabled }}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ .Release.Name }}-restart-kyverno-pods
  namespace: {{ .Release.Namespace }}
rules:
  - apiGroups:
      - apps
    resources:
      - deployments
    resourceNames:
      - kyverno
      - policy-reporter
      - policy-reporter-ui
      - policy-reporter-kyverno-plugin
    verbs:
      - list
      - get
      - patch
      - watch
{{- end }}
